/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : CS2.c
**     Project     : USBSTACK
**     Processor   : MK60DN512ZVLQ10
**     Component   : CriticalSection
**     Version     : Component 01.006, Driver 01.00, CPU db: 3.00.001
**     Repository  : My Components
**     Compiler    : GNU C Compiler
**     Date/Time   : 2016-09-07, 23:22, # CodeGen: 0
**     Abstract    :
**
**     Settings    :
**          Component name                                 : CS2
**          Use Processor Expert Default                   : no
**          Use FreeRTOS                                   : no
**     Contents    :
**         CriticalVariable - void CS2_CriticalVariable(void);
**         EnterCritical    - void CS2_EnterCritical(void);
**         ExitCritical     - void CS2_ExitCritical(void);
**
**     License   : Open Source (LGPL)
**     Copyright : Erich Styger, 2014, all rights reserved.
**     Web       : www.mcuoneclipse.com
**     This an open source software implementing a driver using Processor Expert.
**     This is a free software and is opened for education, research and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file CS2.c
** @version 01.00
** @brief
**
*/         
/*!
**  @addtogroup CS2_module CS2 module documentation
**  @{
*/         

/* MODULE CS2. */

#include "CS2.h"

/*
** ===================================================================
**     Method      :  CS2_CriticalVariable (component CriticalSection)
**     Description :
**         Defines a variable if necessary. This is a macro.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void CS2_CriticalVariable(void)
{
  *** Implemented as macro in the header file CS2.h
}
*/

/*
** ===================================================================
**     Method      :  CS2_EnterCritical (component CriticalSection)
**     Description :
**         Enters a critical section
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void CS2_EnterCritical(void)
{
  *** Implemented as macro in the header file CS2.h
}
*/

/*
** ===================================================================
**     Method      :  CS2_ExitCritical (component CriticalSection)
**     Description :
**         Exits a critical section
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void CS2_ExitCritical(void)
{
  *** Implemented as macro in the header file CS2.h
}
*/

/* END CS2. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
